language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
env:
  - PLONE_VERSION=4.3
  - PLONE_VERSION=4.3 TEST_EGGS=plone.app.contenttypes
matrix:
  fast_finish: true
before_install:
  # FIXME: I have no idea how and why six==1.11.0 is being installed
  - pip uninstall -y six
install:
  - python bootstrap.py
  - bin/buildout buildout:test-eggs=$TEST_EGGS annotate
  - bin/buildout buildout:test-eggs=$TEST_EGGS
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage --output-dir=htmlcov
  - pip install --upgrade coveralls
  - coveralls
notifications:
  irc: irc.freenode.org#plone-testing
